// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB45W-Eg1ID_2FAGWHLIx3E2kYSMLy8JmU',
    appId: '1:285453021872:web:46a2277ac46aaa7a814175',
    messagingSenderId: '285453021872',
    projectId: 'kontaku-faf7f',
    authDomain: 'kontaku-faf7f.firebaseapp.com',
    databaseURL: 'https://kontaku-faf7f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kontaku-faf7f.firebasestorage.app',
    measurementId: 'G-EG5BE75KHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhYalIRvr6gHOvbAQY1mc1bMZPor2OYyw',
    appId: '1:285453021872:android:ae903ac2ea1deab7814175',
    messagingSenderId: '285453021872',
    projectId: 'kontaku-faf7f',
    databaseURL: 'https://kontaku-faf7f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kontaku-faf7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiJ_I-We8TYDTYqIWmG_z2cDCNkZQtVRQ',
    appId: '1:285453021872:ios:621d03e3a8b5ec02814175',
    messagingSenderId: '285453021872',
    projectId: 'kontaku-faf7f',
    databaseURL: 'https://kontaku-faf7f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kontaku-faf7f.firebasestorage.app',
    iosBundleId: 'com.example.kontaku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiJ_I-We8TYDTYqIWmG_z2cDCNkZQtVRQ',
    appId: '1:285453021872:ios:621d03e3a8b5ec02814175',
    messagingSenderId: '285453021872',
    projectId: 'kontaku-faf7f',
    databaseURL: 'https://kontaku-faf7f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kontaku-faf7f.firebasestorage.app',
    iosBundleId: 'com.example.kontaku',
  );

}